### ISSUE TITLE
FR: FontAwesome also as navigation images?

### ISSUE THREAD

**Issue by jscholtysik** [madeyourday/contao-navigation-image#2]
Enhancement of  this extension to also support icon fonts like FontAwesome as navigation images.

My idea would be that FontAwesome could also be included as navigation "images":
- In a vertical navigation on the left or right side of the menu entry
- In a horizontal navigation on top or bottom of the menu entry and centered related to the width of the menu entry or besides the menu entry on the left or right side
- In a drop down menu also on the left or right side of a menu entry

Thanks in advance.

Joachim

**Comment by ausi** [comment]
This extension is no longer in active development.

**Comment by jscholtysik** [comment]
What a pity!

**Comment by ausi** [comment]
As an alternative you can copy the contents of [dca/tl_page.php](https://github.com/madeyourday/contao-navigation-image/blob/master/dca/tl_page.php) into your _system/config/dcaconfig.php_ and modify it for your needs.

**Comment by jscholtysik** [comment]
Thanks, I will try it, but don't expect any great solutions, because I'm no programmer...
