### ISSUE TITLE
Images in Navigation are automatically resized to 100px width

### ISSUE THREAD

**Issue by laudanju** [madeyourday/contao-navigation-image#3]
Any way to fix this?
The issue is that due to the applied CSS, the image will be larger than 100px in width and thus will appear blurry.

**Comment by ausi** [comment]
You can create a customized [_nav_image.html5_](https://github.com/madeyourday/contao-navigation-image/blob/4880a7c20301658bc489de6902bf86adca61905b/templates/nav_image.html5) template and replace `100, 100,` with the size you want to use, or `0, 0,` if you don’t want to resize the images.

Please note: This extension is no longer in active development.

**Comment by laudanju** [comment]
Thank you for the quick answer. Works like a charm. Thank you!
